return {
  "nvim-treesitter/nvim-treesitter",
  lazy = false,
  branch = "main",
  build = ":TSUpdate",
  opts = {
    highlight = { enable = true },
    indent = { enable = true },
    auto_install = { enable = true },
    ensure_installed = {
      "bitbake",
      "c",
      "cmake",
      "comment",
      "json",
      "lua",
      "markdown",
      "markdown_inline",
      "python",
      "rust",
      "toml",
      "yaml",
    },
  },
}
